packages:
  - "packages/*"

packageExtensions:
  antd:
    peerDependencies:
      "@types/react": "@18.3.1"
  "@ant-design/icons":
    peerDependencies:
      "@types/react": "@18.3.1"
  react-router-dom:
    peerDependencies:
      "@types/react": "@18.3.1"
  react-router:
    peerDependencies:
      "@types/react": "@18.3.1"
