
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NotificationRule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NotificationRule
 * 
 */
export type NotificationRuleModel = runtime.Types.Result.DefaultSelection<Prisma.$NotificationRulePayload>

export type AggregateNotificationRule = {
  _count: NotificationRuleCountAggregateOutputType | null
  _avg: NotificationRuleAvgAggregateOutputType | null
  _sum: NotificationRuleSumAggregateOutputType | null
  _min: NotificationRuleMinAggregateOutputType | null
  _max: NotificationRuleMaxAggregateOutputType | null
}

export type NotificationRuleAvgAggregateOutputType = {
  consecutiveFailures: number | null
  cooldownMinutes: number | null
}

export type NotificationRuleSumAggregateOutputType = {
  consecutiveFailures: number | null
  cooldownMinutes: number | null
}

export type NotificationRuleMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  name: string | null
  enabled: boolean | null
  scopeType: $Enums.NotificationScopeType | null
  hostId: string | null
  endpointId: string | null
  consecutiveFailures: number | null
  cooldownMinutes: number | null
  notifyOnRecovery: boolean | null
  channelId: string | null
}

export type NotificationRuleMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  name: string | null
  enabled: boolean | null
  scopeType: $Enums.NotificationScopeType | null
  hostId: string | null
  endpointId: string | null
  consecutiveFailures: number | null
  cooldownMinutes: number | null
  notifyOnRecovery: boolean | null
  channelId: string | null
}

export type NotificationRuleCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  name: number
  enabled: number
  scopeType: number
  hostId: number
  endpointId: number
  consecutiveFailures: number
  cooldownMinutes: number
  notifyOnRecovery: number
  channelId: number
  _all: number
}


export type NotificationRuleAvgAggregateInputType = {
  consecutiveFailures?: true
  cooldownMinutes?: true
}

export type NotificationRuleSumAggregateInputType = {
  consecutiveFailures?: true
  cooldownMinutes?: true
}

export type NotificationRuleMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  enabled?: true
  scopeType?: true
  hostId?: true
  endpointId?: true
  consecutiveFailures?: true
  cooldownMinutes?: true
  notifyOnRecovery?: true
  channelId?: true
}

export type NotificationRuleMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  enabled?: true
  scopeType?: true
  hostId?: true
  endpointId?: true
  consecutiveFailures?: true
  cooldownMinutes?: true
  notifyOnRecovery?: true
  channelId?: true
}

export type NotificationRuleCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  enabled?: true
  scopeType?: true
  hostId?: true
  endpointId?: true
  consecutiveFailures?: true
  cooldownMinutes?: true
  notifyOnRecovery?: true
  channelId?: true
  _all?: true
}

export type NotificationRuleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NotificationRule to aggregate.
   */
  where?: Prisma.NotificationRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationRules to fetch.
   */
  orderBy?: Prisma.NotificationRuleOrderByWithRelationInput | Prisma.NotificationRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NotificationRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NotificationRules
  **/
  _count?: true | NotificationRuleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NotificationRuleAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NotificationRuleSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NotificationRuleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NotificationRuleMaxAggregateInputType
}

export type GetNotificationRuleAggregateType<T extends NotificationRuleAggregateArgs> = {
      [P in keyof T & keyof AggregateNotificationRule]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNotificationRule[P]>
    : Prisma.GetScalarType<T[P], AggregateNotificationRule[P]>
}




export type NotificationRuleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotificationRuleWhereInput
  orderBy?: Prisma.NotificationRuleOrderByWithAggregationInput | Prisma.NotificationRuleOrderByWithAggregationInput[]
  by: Prisma.NotificationRuleScalarFieldEnum[] | Prisma.NotificationRuleScalarFieldEnum
  having?: Prisma.NotificationRuleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NotificationRuleCountAggregateInputType | true
  _avg?: NotificationRuleAvgAggregateInputType
  _sum?: NotificationRuleSumAggregateInputType
  _min?: NotificationRuleMinAggregateInputType
  _max?: NotificationRuleMaxAggregateInputType
}

export type NotificationRuleGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  name: string
  enabled: boolean
  scopeType: $Enums.NotificationScopeType
  hostId: string | null
  endpointId: string | null
  consecutiveFailures: number
  cooldownMinutes: number
  notifyOnRecovery: boolean
  channelId: string
  _count: NotificationRuleCountAggregateOutputType | null
  _avg: NotificationRuleAvgAggregateOutputType | null
  _sum: NotificationRuleSumAggregateOutputType | null
  _min: NotificationRuleMinAggregateOutputType | null
  _max: NotificationRuleMaxAggregateOutputType | null
}

type GetNotificationRuleGroupByPayload<T extends NotificationRuleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NotificationRuleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NotificationRuleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NotificationRuleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NotificationRuleGroupByOutputType[P]>
      }
    >
  >



export type NotificationRuleWhereInput = {
  AND?: Prisma.NotificationRuleWhereInput | Prisma.NotificationRuleWhereInput[]
  OR?: Prisma.NotificationRuleWhereInput[]
  NOT?: Prisma.NotificationRuleWhereInput | Prisma.NotificationRuleWhereInput[]
  id?: Prisma.StringFilter<"NotificationRule"> | string
  createdAt?: Prisma.DateTimeFilter<"NotificationRule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NotificationRule"> | Date | string
  name?: Prisma.StringFilter<"NotificationRule"> | string
  enabled?: Prisma.BoolFilter<"NotificationRule"> | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFilter<"NotificationRule"> | $Enums.NotificationScopeType
  hostId?: Prisma.StringNullableFilter<"NotificationRule"> | string | null
  endpointId?: Prisma.StringNullableFilter<"NotificationRule"> | string | null
  consecutiveFailures?: Prisma.IntFilter<"NotificationRule"> | number
  cooldownMinutes?: Prisma.IntFilter<"NotificationRule"> | number
  notifyOnRecovery?: Prisma.BoolFilter<"NotificationRule"> | boolean
  channelId?: Prisma.StringFilter<"NotificationRule"> | string
  channel?: Prisma.XOR<Prisma.NotificationChannelScalarRelationFilter, Prisma.NotificationChannelWhereInput>
  host?: Prisma.XOR<Prisma.ServiceNullableScalarRelationFilter, Prisma.ServiceWhereInput> | null
  endpoint?: Prisma.XOR<Prisma.EndPointNullableScalarRelationFilter, Prisma.EndPointWhereInput> | null
}

export type NotificationRuleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  scopeType?: Prisma.SortOrder
  hostId?: Prisma.SortOrderInput | Prisma.SortOrder
  endpointId?: Prisma.SortOrderInput | Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  cooldownMinutes?: Prisma.SortOrder
  notifyOnRecovery?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  channel?: Prisma.NotificationChannelOrderByWithRelationInput
  host?: Prisma.ServiceOrderByWithRelationInput
  endpoint?: Prisma.EndPointOrderByWithRelationInput
}

export type NotificationRuleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NotificationRuleWhereInput | Prisma.NotificationRuleWhereInput[]
  OR?: Prisma.NotificationRuleWhereInput[]
  NOT?: Prisma.NotificationRuleWhereInput | Prisma.NotificationRuleWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"NotificationRule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NotificationRule"> | Date | string
  name?: Prisma.StringFilter<"NotificationRule"> | string
  enabled?: Prisma.BoolFilter<"NotificationRule"> | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFilter<"NotificationRule"> | $Enums.NotificationScopeType
  hostId?: Prisma.StringNullableFilter<"NotificationRule"> | string | null
  endpointId?: Prisma.StringNullableFilter<"NotificationRule"> | string | null
  consecutiveFailures?: Prisma.IntFilter<"NotificationRule"> | number
  cooldownMinutes?: Prisma.IntFilter<"NotificationRule"> | number
  notifyOnRecovery?: Prisma.BoolFilter<"NotificationRule"> | boolean
  channelId?: Prisma.StringFilter<"NotificationRule"> | string
  channel?: Prisma.XOR<Prisma.NotificationChannelScalarRelationFilter, Prisma.NotificationChannelWhereInput>
  host?: Prisma.XOR<Prisma.ServiceNullableScalarRelationFilter, Prisma.ServiceWhereInput> | null
  endpoint?: Prisma.XOR<Prisma.EndPointNullableScalarRelationFilter, Prisma.EndPointWhereInput> | null
}, "id">

export type NotificationRuleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  scopeType?: Prisma.SortOrder
  hostId?: Prisma.SortOrderInput | Prisma.SortOrder
  endpointId?: Prisma.SortOrderInput | Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  cooldownMinutes?: Prisma.SortOrder
  notifyOnRecovery?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  _count?: Prisma.NotificationRuleCountOrderByAggregateInput
  _avg?: Prisma.NotificationRuleAvgOrderByAggregateInput
  _max?: Prisma.NotificationRuleMaxOrderByAggregateInput
  _min?: Prisma.NotificationRuleMinOrderByAggregateInput
  _sum?: Prisma.NotificationRuleSumOrderByAggregateInput
}

export type NotificationRuleScalarWhereWithAggregatesInput = {
  AND?: Prisma.NotificationRuleScalarWhereWithAggregatesInput | Prisma.NotificationRuleScalarWhereWithAggregatesInput[]
  OR?: Prisma.NotificationRuleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NotificationRuleScalarWhereWithAggregatesInput | Prisma.NotificationRuleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"NotificationRule"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"NotificationRule"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"NotificationRule"> | Date | string
  name?: Prisma.StringWithAggregatesFilter<"NotificationRule"> | string
  enabled?: Prisma.BoolWithAggregatesFilter<"NotificationRule"> | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeWithAggregatesFilter<"NotificationRule"> | $Enums.NotificationScopeType
  hostId?: Prisma.StringNullableWithAggregatesFilter<"NotificationRule"> | string | null
  endpointId?: Prisma.StringNullableWithAggregatesFilter<"NotificationRule"> | string | null
  consecutiveFailures?: Prisma.IntWithAggregatesFilter<"NotificationRule"> | number
  cooldownMinutes?: Prisma.IntWithAggregatesFilter<"NotificationRule"> | number
  notifyOnRecovery?: Prisma.BoolWithAggregatesFilter<"NotificationRule"> | boolean
  channelId?: Prisma.StringWithAggregatesFilter<"NotificationRule"> | string
}

export type NotificationRuleCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
  channel: Prisma.NotificationChannelCreateNestedOneWithoutRulesInput
  host?: Prisma.ServiceCreateNestedOneWithoutNotificationRulesInput
  endpoint?: Prisma.EndPointCreateNestedOneWithoutNotificationRulesInput
}

export type NotificationRuleUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  hostId?: string | null
  endpointId?: string | null
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
  channelId: string
}

export type NotificationRuleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
  channel?: Prisma.NotificationChannelUpdateOneRequiredWithoutRulesNestedInput
  host?: Prisma.ServiceUpdateOneWithoutNotificationRulesNestedInput
  endpoint?: Prisma.EndPointUpdateOneWithoutNotificationRulesNestedInput
}

export type NotificationRuleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  hostId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  endpointId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NotificationRuleCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  hostId?: string | null
  endpointId?: string | null
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
  channelId: string
}

export type NotificationRuleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type NotificationRuleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  hostId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  endpointId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NotificationRuleListRelationFilter = {
  every?: Prisma.NotificationRuleWhereInput
  some?: Prisma.NotificationRuleWhereInput
  none?: Prisma.NotificationRuleWhereInput
}

export type NotificationRuleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NotificationRuleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  scopeType?: Prisma.SortOrder
  hostId?: Prisma.SortOrder
  endpointId?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  cooldownMinutes?: Prisma.SortOrder
  notifyOnRecovery?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
}

export type NotificationRuleAvgOrderByAggregateInput = {
  consecutiveFailures?: Prisma.SortOrder
  cooldownMinutes?: Prisma.SortOrder
}

export type NotificationRuleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  scopeType?: Prisma.SortOrder
  hostId?: Prisma.SortOrder
  endpointId?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  cooldownMinutes?: Prisma.SortOrder
  notifyOnRecovery?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
}

export type NotificationRuleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  scopeType?: Prisma.SortOrder
  hostId?: Prisma.SortOrder
  endpointId?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  cooldownMinutes?: Prisma.SortOrder
  notifyOnRecovery?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
}

export type NotificationRuleSumOrderByAggregateInput = {
  consecutiveFailures?: Prisma.SortOrder
  cooldownMinutes?: Prisma.SortOrder
}

export type NotificationRuleCreateNestedManyWithoutHostInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutHostInput, Prisma.NotificationRuleUncheckedCreateWithoutHostInput> | Prisma.NotificationRuleCreateWithoutHostInput[] | Prisma.NotificationRuleUncheckedCreateWithoutHostInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutHostInput | Prisma.NotificationRuleCreateOrConnectWithoutHostInput[]
  createMany?: Prisma.NotificationRuleCreateManyHostInputEnvelope
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
}

export type NotificationRuleUncheckedCreateNestedManyWithoutHostInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutHostInput, Prisma.NotificationRuleUncheckedCreateWithoutHostInput> | Prisma.NotificationRuleCreateWithoutHostInput[] | Prisma.NotificationRuleUncheckedCreateWithoutHostInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutHostInput | Prisma.NotificationRuleCreateOrConnectWithoutHostInput[]
  createMany?: Prisma.NotificationRuleCreateManyHostInputEnvelope
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
}

export type NotificationRuleUpdateManyWithoutHostNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutHostInput, Prisma.NotificationRuleUncheckedCreateWithoutHostInput> | Prisma.NotificationRuleCreateWithoutHostInput[] | Prisma.NotificationRuleUncheckedCreateWithoutHostInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutHostInput | Prisma.NotificationRuleCreateOrConnectWithoutHostInput[]
  upsert?: Prisma.NotificationRuleUpsertWithWhereUniqueWithoutHostInput | Prisma.NotificationRuleUpsertWithWhereUniqueWithoutHostInput[]
  createMany?: Prisma.NotificationRuleCreateManyHostInputEnvelope
  set?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  disconnect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  delete?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  update?: Prisma.NotificationRuleUpdateWithWhereUniqueWithoutHostInput | Prisma.NotificationRuleUpdateWithWhereUniqueWithoutHostInput[]
  updateMany?: Prisma.NotificationRuleUpdateManyWithWhereWithoutHostInput | Prisma.NotificationRuleUpdateManyWithWhereWithoutHostInput[]
  deleteMany?: Prisma.NotificationRuleScalarWhereInput | Prisma.NotificationRuleScalarWhereInput[]
}

export type NotificationRuleUncheckedUpdateManyWithoutHostNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutHostInput, Prisma.NotificationRuleUncheckedCreateWithoutHostInput> | Prisma.NotificationRuleCreateWithoutHostInput[] | Prisma.NotificationRuleUncheckedCreateWithoutHostInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutHostInput | Prisma.NotificationRuleCreateOrConnectWithoutHostInput[]
  upsert?: Prisma.NotificationRuleUpsertWithWhereUniqueWithoutHostInput | Prisma.NotificationRuleUpsertWithWhereUniqueWithoutHostInput[]
  createMany?: Prisma.NotificationRuleCreateManyHostInputEnvelope
  set?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  disconnect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  delete?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  update?: Prisma.NotificationRuleUpdateWithWhereUniqueWithoutHostInput | Prisma.NotificationRuleUpdateWithWhereUniqueWithoutHostInput[]
  updateMany?: Prisma.NotificationRuleUpdateManyWithWhereWithoutHostInput | Prisma.NotificationRuleUpdateManyWithWhereWithoutHostInput[]
  deleteMany?: Prisma.NotificationRuleScalarWhereInput | Prisma.NotificationRuleScalarWhereInput[]
}

export type NotificationRuleCreateNestedManyWithoutEndpointInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutEndpointInput, Prisma.NotificationRuleUncheckedCreateWithoutEndpointInput> | Prisma.NotificationRuleCreateWithoutEndpointInput[] | Prisma.NotificationRuleUncheckedCreateWithoutEndpointInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutEndpointInput | Prisma.NotificationRuleCreateOrConnectWithoutEndpointInput[]
  createMany?: Prisma.NotificationRuleCreateManyEndpointInputEnvelope
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
}

export type NotificationRuleUncheckedCreateNestedManyWithoutEndpointInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutEndpointInput, Prisma.NotificationRuleUncheckedCreateWithoutEndpointInput> | Prisma.NotificationRuleCreateWithoutEndpointInput[] | Prisma.NotificationRuleUncheckedCreateWithoutEndpointInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutEndpointInput | Prisma.NotificationRuleCreateOrConnectWithoutEndpointInput[]
  createMany?: Prisma.NotificationRuleCreateManyEndpointInputEnvelope
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
}

export type NotificationRuleUpdateManyWithoutEndpointNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutEndpointInput, Prisma.NotificationRuleUncheckedCreateWithoutEndpointInput> | Prisma.NotificationRuleCreateWithoutEndpointInput[] | Prisma.NotificationRuleUncheckedCreateWithoutEndpointInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutEndpointInput | Prisma.NotificationRuleCreateOrConnectWithoutEndpointInput[]
  upsert?: Prisma.NotificationRuleUpsertWithWhereUniqueWithoutEndpointInput | Prisma.NotificationRuleUpsertWithWhereUniqueWithoutEndpointInput[]
  createMany?: Prisma.NotificationRuleCreateManyEndpointInputEnvelope
  set?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  disconnect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  delete?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  update?: Prisma.NotificationRuleUpdateWithWhereUniqueWithoutEndpointInput | Prisma.NotificationRuleUpdateWithWhereUniqueWithoutEndpointInput[]
  updateMany?: Prisma.NotificationRuleUpdateManyWithWhereWithoutEndpointInput | Prisma.NotificationRuleUpdateManyWithWhereWithoutEndpointInput[]
  deleteMany?: Prisma.NotificationRuleScalarWhereInput | Prisma.NotificationRuleScalarWhereInput[]
}

export type NotificationRuleUncheckedUpdateManyWithoutEndpointNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutEndpointInput, Prisma.NotificationRuleUncheckedCreateWithoutEndpointInput> | Prisma.NotificationRuleCreateWithoutEndpointInput[] | Prisma.NotificationRuleUncheckedCreateWithoutEndpointInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutEndpointInput | Prisma.NotificationRuleCreateOrConnectWithoutEndpointInput[]
  upsert?: Prisma.NotificationRuleUpsertWithWhereUniqueWithoutEndpointInput | Prisma.NotificationRuleUpsertWithWhereUniqueWithoutEndpointInput[]
  createMany?: Prisma.NotificationRuleCreateManyEndpointInputEnvelope
  set?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  disconnect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  delete?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  update?: Prisma.NotificationRuleUpdateWithWhereUniqueWithoutEndpointInput | Prisma.NotificationRuleUpdateWithWhereUniqueWithoutEndpointInput[]
  updateMany?: Prisma.NotificationRuleUpdateManyWithWhereWithoutEndpointInput | Prisma.NotificationRuleUpdateManyWithWhereWithoutEndpointInput[]
  deleteMany?: Prisma.NotificationRuleScalarWhereInput | Prisma.NotificationRuleScalarWhereInput[]
}

export type NotificationRuleCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutChannelInput, Prisma.NotificationRuleUncheckedCreateWithoutChannelInput> | Prisma.NotificationRuleCreateWithoutChannelInput[] | Prisma.NotificationRuleUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutChannelInput | Prisma.NotificationRuleCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.NotificationRuleCreateManyChannelInputEnvelope
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
}

export type NotificationRuleUncheckedCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutChannelInput, Prisma.NotificationRuleUncheckedCreateWithoutChannelInput> | Prisma.NotificationRuleCreateWithoutChannelInput[] | Prisma.NotificationRuleUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutChannelInput | Prisma.NotificationRuleCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.NotificationRuleCreateManyChannelInputEnvelope
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
}

export type NotificationRuleUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutChannelInput, Prisma.NotificationRuleUncheckedCreateWithoutChannelInput> | Prisma.NotificationRuleCreateWithoutChannelInput[] | Prisma.NotificationRuleUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutChannelInput | Prisma.NotificationRuleCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.NotificationRuleUpsertWithWhereUniqueWithoutChannelInput | Prisma.NotificationRuleUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.NotificationRuleCreateManyChannelInputEnvelope
  set?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  disconnect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  delete?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  update?: Prisma.NotificationRuleUpdateWithWhereUniqueWithoutChannelInput | Prisma.NotificationRuleUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.NotificationRuleUpdateManyWithWhereWithoutChannelInput | Prisma.NotificationRuleUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.NotificationRuleScalarWhereInput | Prisma.NotificationRuleScalarWhereInput[]
}

export type NotificationRuleUncheckedUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationRuleCreateWithoutChannelInput, Prisma.NotificationRuleUncheckedCreateWithoutChannelInput> | Prisma.NotificationRuleCreateWithoutChannelInput[] | Prisma.NotificationRuleUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.NotificationRuleCreateOrConnectWithoutChannelInput | Prisma.NotificationRuleCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.NotificationRuleUpsertWithWhereUniqueWithoutChannelInput | Prisma.NotificationRuleUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.NotificationRuleCreateManyChannelInputEnvelope
  set?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  disconnect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  delete?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  connect?: Prisma.NotificationRuleWhereUniqueInput | Prisma.NotificationRuleWhereUniqueInput[]
  update?: Prisma.NotificationRuleUpdateWithWhereUniqueWithoutChannelInput | Prisma.NotificationRuleUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.NotificationRuleUpdateManyWithWhereWithoutChannelInput | Prisma.NotificationRuleUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.NotificationRuleScalarWhereInput | Prisma.NotificationRuleScalarWhereInput[]
}

export type EnumNotificationScopeTypeFieldUpdateOperationsInput = {
  set?: $Enums.NotificationScopeType
}

export type NotificationRuleCreateWithoutHostInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
  channel: Prisma.NotificationChannelCreateNestedOneWithoutRulesInput
  endpoint?: Prisma.EndPointCreateNestedOneWithoutNotificationRulesInput
}

export type NotificationRuleUncheckedCreateWithoutHostInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  endpointId?: string | null
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
  channelId: string
}

export type NotificationRuleCreateOrConnectWithoutHostInput = {
  where: Prisma.NotificationRuleWhereUniqueInput
  create: Prisma.XOR<Prisma.NotificationRuleCreateWithoutHostInput, Prisma.NotificationRuleUncheckedCreateWithoutHostInput>
}

export type NotificationRuleCreateManyHostInputEnvelope = {
  data: Prisma.NotificationRuleCreateManyHostInput | Prisma.NotificationRuleCreateManyHostInput[]
}

export type NotificationRuleUpsertWithWhereUniqueWithoutHostInput = {
  where: Prisma.NotificationRuleWhereUniqueInput
  update: Prisma.XOR<Prisma.NotificationRuleUpdateWithoutHostInput, Prisma.NotificationRuleUncheckedUpdateWithoutHostInput>
  create: Prisma.XOR<Prisma.NotificationRuleCreateWithoutHostInput, Prisma.NotificationRuleUncheckedCreateWithoutHostInput>
}

export type NotificationRuleUpdateWithWhereUniqueWithoutHostInput = {
  where: Prisma.NotificationRuleWhereUniqueInput
  data: Prisma.XOR<Prisma.NotificationRuleUpdateWithoutHostInput, Prisma.NotificationRuleUncheckedUpdateWithoutHostInput>
}

export type NotificationRuleUpdateManyWithWhereWithoutHostInput = {
  where: Prisma.NotificationRuleScalarWhereInput
  data: Prisma.XOR<Prisma.NotificationRuleUpdateManyMutationInput, Prisma.NotificationRuleUncheckedUpdateManyWithoutHostInput>
}

export type NotificationRuleScalarWhereInput = {
  AND?: Prisma.NotificationRuleScalarWhereInput | Prisma.NotificationRuleScalarWhereInput[]
  OR?: Prisma.NotificationRuleScalarWhereInput[]
  NOT?: Prisma.NotificationRuleScalarWhereInput | Prisma.NotificationRuleScalarWhereInput[]
  id?: Prisma.StringFilter<"NotificationRule"> | string
  createdAt?: Prisma.DateTimeFilter<"NotificationRule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NotificationRule"> | Date | string
  name?: Prisma.StringFilter<"NotificationRule"> | string
  enabled?: Prisma.BoolFilter<"NotificationRule"> | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFilter<"NotificationRule"> | $Enums.NotificationScopeType
  hostId?: Prisma.StringNullableFilter<"NotificationRule"> | string | null
  endpointId?: Prisma.StringNullableFilter<"NotificationRule"> | string | null
  consecutiveFailures?: Prisma.IntFilter<"NotificationRule"> | number
  cooldownMinutes?: Prisma.IntFilter<"NotificationRule"> | number
  notifyOnRecovery?: Prisma.BoolFilter<"NotificationRule"> | boolean
  channelId?: Prisma.StringFilter<"NotificationRule"> | string
}

export type NotificationRuleCreateWithoutEndpointInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
  channel: Prisma.NotificationChannelCreateNestedOneWithoutRulesInput
  host?: Prisma.ServiceCreateNestedOneWithoutNotificationRulesInput
}

export type NotificationRuleUncheckedCreateWithoutEndpointInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  hostId?: string | null
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
  channelId: string
}

export type NotificationRuleCreateOrConnectWithoutEndpointInput = {
  where: Prisma.NotificationRuleWhereUniqueInput
  create: Prisma.XOR<Prisma.NotificationRuleCreateWithoutEndpointInput, Prisma.NotificationRuleUncheckedCreateWithoutEndpointInput>
}

export type NotificationRuleCreateManyEndpointInputEnvelope = {
  data: Prisma.NotificationRuleCreateManyEndpointInput | Prisma.NotificationRuleCreateManyEndpointInput[]
}

export type NotificationRuleUpsertWithWhereUniqueWithoutEndpointInput = {
  where: Prisma.NotificationRuleWhereUniqueInput
  update: Prisma.XOR<Prisma.NotificationRuleUpdateWithoutEndpointInput, Prisma.NotificationRuleUncheckedUpdateWithoutEndpointInput>
  create: Prisma.XOR<Prisma.NotificationRuleCreateWithoutEndpointInput, Prisma.NotificationRuleUncheckedCreateWithoutEndpointInput>
}

export type NotificationRuleUpdateWithWhereUniqueWithoutEndpointInput = {
  where: Prisma.NotificationRuleWhereUniqueInput
  data: Prisma.XOR<Prisma.NotificationRuleUpdateWithoutEndpointInput, Prisma.NotificationRuleUncheckedUpdateWithoutEndpointInput>
}

export type NotificationRuleUpdateManyWithWhereWithoutEndpointInput = {
  where: Prisma.NotificationRuleScalarWhereInput
  data: Prisma.XOR<Prisma.NotificationRuleUpdateManyMutationInput, Prisma.NotificationRuleUncheckedUpdateManyWithoutEndpointInput>
}

export type NotificationRuleCreateWithoutChannelInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
  host?: Prisma.ServiceCreateNestedOneWithoutNotificationRulesInput
  endpoint?: Prisma.EndPointCreateNestedOneWithoutNotificationRulesInput
}

export type NotificationRuleUncheckedCreateWithoutChannelInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  hostId?: string | null
  endpointId?: string | null
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
}

export type NotificationRuleCreateOrConnectWithoutChannelInput = {
  where: Prisma.NotificationRuleWhereUniqueInput
  create: Prisma.XOR<Prisma.NotificationRuleCreateWithoutChannelInput, Prisma.NotificationRuleUncheckedCreateWithoutChannelInput>
}

export type NotificationRuleCreateManyChannelInputEnvelope = {
  data: Prisma.NotificationRuleCreateManyChannelInput | Prisma.NotificationRuleCreateManyChannelInput[]
}

export type NotificationRuleUpsertWithWhereUniqueWithoutChannelInput = {
  where: Prisma.NotificationRuleWhereUniqueInput
  update: Prisma.XOR<Prisma.NotificationRuleUpdateWithoutChannelInput, Prisma.NotificationRuleUncheckedUpdateWithoutChannelInput>
  create: Prisma.XOR<Prisma.NotificationRuleCreateWithoutChannelInput, Prisma.NotificationRuleUncheckedCreateWithoutChannelInput>
}

export type NotificationRuleUpdateWithWhereUniqueWithoutChannelInput = {
  where: Prisma.NotificationRuleWhereUniqueInput
  data: Prisma.XOR<Prisma.NotificationRuleUpdateWithoutChannelInput, Prisma.NotificationRuleUncheckedUpdateWithoutChannelInput>
}

export type NotificationRuleUpdateManyWithWhereWithoutChannelInput = {
  where: Prisma.NotificationRuleScalarWhereInput
  data: Prisma.XOR<Prisma.NotificationRuleUpdateManyMutationInput, Prisma.NotificationRuleUncheckedUpdateManyWithoutChannelInput>
}

export type NotificationRuleCreateManyHostInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  endpointId?: string | null
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
  channelId: string
}

export type NotificationRuleUpdateWithoutHostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
  channel?: Prisma.NotificationChannelUpdateOneRequiredWithoutRulesNestedInput
  endpoint?: Prisma.EndPointUpdateOneWithoutNotificationRulesNestedInput
}

export type NotificationRuleUncheckedUpdateWithoutHostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  endpointId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NotificationRuleUncheckedUpdateManyWithoutHostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  endpointId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NotificationRuleCreateManyEndpointInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  hostId?: string | null
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
  channelId: string
}

export type NotificationRuleUpdateWithoutEndpointInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
  channel?: Prisma.NotificationChannelUpdateOneRequiredWithoutRulesNestedInput
  host?: Prisma.ServiceUpdateOneWithoutNotificationRulesNestedInput
}

export type NotificationRuleUncheckedUpdateWithoutEndpointInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  hostId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NotificationRuleUncheckedUpdateManyWithoutEndpointInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  hostId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NotificationRuleCreateManyChannelInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  enabled?: boolean
  scopeType?: $Enums.NotificationScopeType
  hostId?: string | null
  endpointId?: string | null
  consecutiveFailures?: number
  cooldownMinutes?: number
  notifyOnRecovery?: boolean
}

export type NotificationRuleUpdateWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
  host?: Prisma.ServiceUpdateOneWithoutNotificationRulesNestedInput
  endpoint?: Prisma.EndPointUpdateOneWithoutNotificationRulesNestedInput
}

export type NotificationRuleUncheckedUpdateWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  hostId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  endpointId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type NotificationRuleUncheckedUpdateManyWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scopeType?: Prisma.EnumNotificationScopeTypeFieldUpdateOperationsInput | $Enums.NotificationScopeType
  hostId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  endpointId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  notifyOnRecovery?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type NotificationRuleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  enabled?: boolean
  scopeType?: boolean
  hostId?: boolean
  endpointId?: boolean
  consecutiveFailures?: boolean
  cooldownMinutes?: boolean
  notifyOnRecovery?: boolean
  channelId?: boolean
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
  host?: boolean | Prisma.NotificationRule$hostArgs<ExtArgs>
  endpoint?: boolean | Prisma.NotificationRule$endpointArgs<ExtArgs>
}, ExtArgs["result"]["notificationRule"]>

export type NotificationRuleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  enabled?: boolean
  scopeType?: boolean
  hostId?: boolean
  endpointId?: boolean
  consecutiveFailures?: boolean
  cooldownMinutes?: boolean
  notifyOnRecovery?: boolean
  channelId?: boolean
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
  host?: boolean | Prisma.NotificationRule$hostArgs<ExtArgs>
  endpoint?: boolean | Prisma.NotificationRule$endpointArgs<ExtArgs>
}, ExtArgs["result"]["notificationRule"]>

export type NotificationRuleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  enabled?: boolean
  scopeType?: boolean
  hostId?: boolean
  endpointId?: boolean
  consecutiveFailures?: boolean
  cooldownMinutes?: boolean
  notifyOnRecovery?: boolean
  channelId?: boolean
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
  host?: boolean | Prisma.NotificationRule$hostArgs<ExtArgs>
  endpoint?: boolean | Prisma.NotificationRule$endpointArgs<ExtArgs>
}, ExtArgs["result"]["notificationRule"]>

export type NotificationRuleSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  enabled?: boolean
  scopeType?: boolean
  hostId?: boolean
  endpointId?: boolean
  consecutiveFailures?: boolean
  cooldownMinutes?: boolean
  notifyOnRecovery?: boolean
  channelId?: boolean
}

export type NotificationRuleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "name" | "enabled" | "scopeType" | "hostId" | "endpointId" | "consecutiveFailures" | "cooldownMinutes" | "notifyOnRecovery" | "channelId", ExtArgs["result"]["notificationRule"]>
export type NotificationRuleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
  host?: boolean | Prisma.NotificationRule$hostArgs<ExtArgs>
  endpoint?: boolean | Prisma.NotificationRule$endpointArgs<ExtArgs>
}
export type NotificationRuleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
  host?: boolean | Prisma.NotificationRule$hostArgs<ExtArgs>
  endpoint?: boolean | Prisma.NotificationRule$endpointArgs<ExtArgs>
}
export type NotificationRuleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
  host?: boolean | Prisma.NotificationRule$hostArgs<ExtArgs>
  endpoint?: boolean | Prisma.NotificationRule$endpointArgs<ExtArgs>
}

export type $NotificationRulePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NotificationRule"
  objects: {
    channel: Prisma.$NotificationChannelPayload<ExtArgs>
    host: Prisma.$ServicePayload<ExtArgs> | null
    endpoint: Prisma.$EndPointPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    name: string
    enabled: boolean
    scopeType: $Enums.NotificationScopeType
    hostId: string | null
    endpointId: string | null
    consecutiveFailures: number
    cooldownMinutes: number
    notifyOnRecovery: boolean
    channelId: string
  }, ExtArgs["result"]["notificationRule"]>
  composites: {}
}

export type NotificationRuleGetPayload<S extends boolean | null | undefined | NotificationRuleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload, S>

export type NotificationRuleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NotificationRuleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NotificationRuleCountAggregateInputType | true
  }

export interface NotificationRuleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NotificationRule'], meta: { name: 'NotificationRule' } }
  /**
   * Find zero or one NotificationRule that matches the filter.
   * @param {NotificationRuleFindUniqueArgs} args - Arguments to find a NotificationRule
   * @example
   * // Get one NotificationRule
   * const notificationRule = await prisma.notificationRule.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NotificationRuleFindUniqueArgs>(args: Prisma.SelectSubset<T, NotificationRuleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NotificationRuleClient<runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NotificationRule that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NotificationRuleFindUniqueOrThrowArgs} args - Arguments to find a NotificationRule
   * @example
   * // Get one NotificationRule
   * const notificationRule = await prisma.notificationRule.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NotificationRuleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NotificationRuleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotificationRuleClient<runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NotificationRule that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationRuleFindFirstArgs} args - Arguments to find a NotificationRule
   * @example
   * // Get one NotificationRule
   * const notificationRule = await prisma.notificationRule.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NotificationRuleFindFirstArgs>(args?: Prisma.SelectSubset<T, NotificationRuleFindFirstArgs<ExtArgs>>): Prisma.Prisma__NotificationRuleClient<runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NotificationRule that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationRuleFindFirstOrThrowArgs} args - Arguments to find a NotificationRule
   * @example
   * // Get one NotificationRule
   * const notificationRule = await prisma.notificationRule.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NotificationRuleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NotificationRuleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotificationRuleClient<runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NotificationRules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationRuleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NotificationRules
   * const notificationRules = await prisma.notificationRule.findMany()
   * 
   * // Get first 10 NotificationRules
   * const notificationRules = await prisma.notificationRule.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const notificationRuleWithIdOnly = await prisma.notificationRule.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NotificationRuleFindManyArgs>(args?: Prisma.SelectSubset<T, NotificationRuleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NotificationRule.
   * @param {NotificationRuleCreateArgs} args - Arguments to create a NotificationRule.
   * @example
   * // Create one NotificationRule
   * const NotificationRule = await prisma.notificationRule.create({
   *   data: {
   *     // ... data to create a NotificationRule
   *   }
   * })
   * 
   */
  create<T extends NotificationRuleCreateArgs>(args: Prisma.SelectSubset<T, NotificationRuleCreateArgs<ExtArgs>>): Prisma.Prisma__NotificationRuleClient<runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NotificationRules.
   * @param {NotificationRuleCreateManyArgs} args - Arguments to create many NotificationRules.
   * @example
   * // Create many NotificationRules
   * const notificationRule = await prisma.notificationRule.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NotificationRuleCreateManyArgs>(args?: Prisma.SelectSubset<T, NotificationRuleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NotificationRules and returns the data saved in the database.
   * @param {NotificationRuleCreateManyAndReturnArgs} args - Arguments to create many NotificationRules.
   * @example
   * // Create many NotificationRules
   * const notificationRule = await prisma.notificationRule.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NotificationRules and only return the `id`
   * const notificationRuleWithIdOnly = await prisma.notificationRule.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NotificationRuleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NotificationRuleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NotificationRule.
   * @param {NotificationRuleDeleteArgs} args - Arguments to delete one NotificationRule.
   * @example
   * // Delete one NotificationRule
   * const NotificationRule = await prisma.notificationRule.delete({
   *   where: {
   *     // ... filter to delete one NotificationRule
   *   }
   * })
   * 
   */
  delete<T extends NotificationRuleDeleteArgs>(args: Prisma.SelectSubset<T, NotificationRuleDeleteArgs<ExtArgs>>): Prisma.Prisma__NotificationRuleClient<runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NotificationRule.
   * @param {NotificationRuleUpdateArgs} args - Arguments to update one NotificationRule.
   * @example
   * // Update one NotificationRule
   * const notificationRule = await prisma.notificationRule.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NotificationRuleUpdateArgs>(args: Prisma.SelectSubset<T, NotificationRuleUpdateArgs<ExtArgs>>): Prisma.Prisma__NotificationRuleClient<runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NotificationRules.
   * @param {NotificationRuleDeleteManyArgs} args - Arguments to filter NotificationRules to delete.
   * @example
   * // Delete a few NotificationRules
   * const { count } = await prisma.notificationRule.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NotificationRuleDeleteManyArgs>(args?: Prisma.SelectSubset<T, NotificationRuleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NotificationRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationRuleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NotificationRules
   * const notificationRule = await prisma.notificationRule.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NotificationRuleUpdateManyArgs>(args: Prisma.SelectSubset<T, NotificationRuleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NotificationRules and returns the data updated in the database.
   * @param {NotificationRuleUpdateManyAndReturnArgs} args - Arguments to update many NotificationRules.
   * @example
   * // Update many NotificationRules
   * const notificationRule = await prisma.notificationRule.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NotificationRules and only return the `id`
   * const notificationRuleWithIdOnly = await prisma.notificationRule.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NotificationRuleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NotificationRuleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NotificationRule.
   * @param {NotificationRuleUpsertArgs} args - Arguments to update or create a NotificationRule.
   * @example
   * // Update or create a NotificationRule
   * const notificationRule = await prisma.notificationRule.upsert({
   *   create: {
   *     // ... data to create a NotificationRule
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NotificationRule we want to update
   *   }
   * })
   */
  upsert<T extends NotificationRuleUpsertArgs>(args: Prisma.SelectSubset<T, NotificationRuleUpsertArgs<ExtArgs>>): Prisma.Prisma__NotificationRuleClient<runtime.Types.Result.GetResult<Prisma.$NotificationRulePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NotificationRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationRuleCountArgs} args - Arguments to filter NotificationRules to count.
   * @example
   * // Count the number of NotificationRules
   * const count = await prisma.notificationRule.count({
   *   where: {
   *     // ... the filter for the NotificationRules we want to count
   *   }
   * })
  **/
  count<T extends NotificationRuleCountArgs>(
    args?: Prisma.Subset<T, NotificationRuleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NotificationRuleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NotificationRule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationRuleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NotificationRuleAggregateArgs>(args: Prisma.Subset<T, NotificationRuleAggregateArgs>): Prisma.PrismaPromise<GetNotificationRuleAggregateType<T>>

  /**
   * Group by NotificationRule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationRuleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NotificationRuleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NotificationRuleGroupByArgs['orderBy'] }
      : { orderBy?: NotificationRuleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NotificationRuleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNotificationRuleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NotificationRule model
 */
readonly fields: NotificationRuleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NotificationRule.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NotificationRuleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  channel<T extends Prisma.NotificationChannelDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NotificationChannelDefaultArgs<ExtArgs>>): Prisma.Prisma__NotificationChannelClient<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  host<T extends Prisma.NotificationRule$hostArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NotificationRule$hostArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  endpoint<T extends Prisma.NotificationRule$endpointArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NotificationRule$endpointArgs<ExtArgs>>): Prisma.Prisma__EndPointClient<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NotificationRule model
 */
export interface NotificationRuleFieldRefs {
  readonly id: Prisma.FieldRef<"NotificationRule", 'String'>
  readonly createdAt: Prisma.FieldRef<"NotificationRule", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"NotificationRule", 'DateTime'>
  readonly name: Prisma.FieldRef<"NotificationRule", 'String'>
  readonly enabled: Prisma.FieldRef<"NotificationRule", 'Boolean'>
  readonly scopeType: Prisma.FieldRef<"NotificationRule", 'NotificationScopeType'>
  readonly hostId: Prisma.FieldRef<"NotificationRule", 'String'>
  readonly endpointId: Prisma.FieldRef<"NotificationRule", 'String'>
  readonly consecutiveFailures: Prisma.FieldRef<"NotificationRule", 'Int'>
  readonly cooldownMinutes: Prisma.FieldRef<"NotificationRule", 'Int'>
  readonly notifyOnRecovery: Prisma.FieldRef<"NotificationRule", 'Boolean'>
  readonly channelId: Prisma.FieldRef<"NotificationRule", 'String'>
}
    

// Custom InputTypes
/**
 * NotificationRule findUnique
 */
export type NotificationRuleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleInclude<ExtArgs> | null
  /**
   * Filter, which NotificationRule to fetch.
   */
  where: Prisma.NotificationRuleWhereUniqueInput
}

/**
 * NotificationRule findUniqueOrThrow
 */
export type NotificationRuleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleInclude<ExtArgs> | null
  /**
   * Filter, which NotificationRule to fetch.
   */
  where: Prisma.NotificationRuleWhereUniqueInput
}

/**
 * NotificationRule findFirst
 */
export type NotificationRuleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleInclude<ExtArgs> | null
  /**
   * Filter, which NotificationRule to fetch.
   */
  where?: Prisma.NotificationRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationRules to fetch.
   */
  orderBy?: Prisma.NotificationRuleOrderByWithRelationInput | Prisma.NotificationRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NotificationRules.
   */
  cursor?: Prisma.NotificationRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NotificationRules.
   */
  distinct?: Prisma.NotificationRuleScalarFieldEnum | Prisma.NotificationRuleScalarFieldEnum[]
}

/**
 * NotificationRule findFirstOrThrow
 */
export type NotificationRuleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleInclude<ExtArgs> | null
  /**
   * Filter, which NotificationRule to fetch.
   */
  where?: Prisma.NotificationRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationRules to fetch.
   */
  orderBy?: Prisma.NotificationRuleOrderByWithRelationInput | Prisma.NotificationRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NotificationRules.
   */
  cursor?: Prisma.NotificationRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NotificationRules.
   */
  distinct?: Prisma.NotificationRuleScalarFieldEnum | Prisma.NotificationRuleScalarFieldEnum[]
}

/**
 * NotificationRule findMany
 */
export type NotificationRuleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleInclude<ExtArgs> | null
  /**
   * Filter, which NotificationRules to fetch.
   */
  where?: Prisma.NotificationRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationRules to fetch.
   */
  orderBy?: Prisma.NotificationRuleOrderByWithRelationInput | Prisma.NotificationRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NotificationRules.
   */
  cursor?: Prisma.NotificationRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationRules.
   */
  skip?: number
  distinct?: Prisma.NotificationRuleScalarFieldEnum | Prisma.NotificationRuleScalarFieldEnum[]
}

/**
 * NotificationRule create
 */
export type NotificationRuleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleInclude<ExtArgs> | null
  /**
   * The data needed to create a NotificationRule.
   */
  data: Prisma.XOR<Prisma.NotificationRuleCreateInput, Prisma.NotificationRuleUncheckedCreateInput>
}

/**
 * NotificationRule createMany
 */
export type NotificationRuleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NotificationRules.
   */
  data: Prisma.NotificationRuleCreateManyInput | Prisma.NotificationRuleCreateManyInput[]
}

/**
 * NotificationRule createManyAndReturn
 */
export type NotificationRuleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * The data used to create many NotificationRules.
   */
  data: Prisma.NotificationRuleCreateManyInput | Prisma.NotificationRuleCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * NotificationRule update
 */
export type NotificationRuleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleInclude<ExtArgs> | null
  /**
   * The data needed to update a NotificationRule.
   */
  data: Prisma.XOR<Prisma.NotificationRuleUpdateInput, Prisma.NotificationRuleUncheckedUpdateInput>
  /**
   * Choose, which NotificationRule to update.
   */
  where: Prisma.NotificationRuleWhereUniqueInput
}

/**
 * NotificationRule updateMany
 */
export type NotificationRuleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NotificationRules.
   */
  data: Prisma.XOR<Prisma.NotificationRuleUpdateManyMutationInput, Prisma.NotificationRuleUncheckedUpdateManyInput>
  /**
   * Filter which NotificationRules to update
   */
  where?: Prisma.NotificationRuleWhereInput
  /**
   * Limit how many NotificationRules to update.
   */
  limit?: number
}

/**
 * NotificationRule updateManyAndReturn
 */
export type NotificationRuleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * The data used to update NotificationRules.
   */
  data: Prisma.XOR<Prisma.NotificationRuleUpdateManyMutationInput, Prisma.NotificationRuleUncheckedUpdateManyInput>
  /**
   * Filter which NotificationRules to update
   */
  where?: Prisma.NotificationRuleWhereInput
  /**
   * Limit how many NotificationRules to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * NotificationRule upsert
 */
export type NotificationRuleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleInclude<ExtArgs> | null
  /**
   * The filter to search for the NotificationRule to update in case it exists.
   */
  where: Prisma.NotificationRuleWhereUniqueInput
  /**
   * In case the NotificationRule found by the `where` argument doesn't exist, create a new NotificationRule with this data.
   */
  create: Prisma.XOR<Prisma.NotificationRuleCreateInput, Prisma.NotificationRuleUncheckedCreateInput>
  /**
   * In case the NotificationRule was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NotificationRuleUpdateInput, Prisma.NotificationRuleUncheckedUpdateInput>
}

/**
 * NotificationRule delete
 */
export type NotificationRuleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleInclude<ExtArgs> | null
  /**
   * Filter which NotificationRule to delete.
   */
  where: Prisma.NotificationRuleWhereUniqueInput
}

/**
 * NotificationRule deleteMany
 */
export type NotificationRuleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NotificationRules to delete
   */
  where?: Prisma.NotificationRuleWhereInput
  /**
   * Limit how many NotificationRules to delete.
   */
  limit?: number
}

/**
 * NotificationRule.host
 */
export type NotificationRule$hostArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  where?: Prisma.ServiceWhereInput
}

/**
 * NotificationRule.endpoint
 */
export type NotificationRule$endpointArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointInclude<ExtArgs> | null
  where?: Prisma.EndPointWhereInput
}

/**
 * NotificationRule without action
 */
export type NotificationRuleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationRule
   */
  select?: Prisma.NotificationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationRule
   */
  omit?: Prisma.NotificationRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationRuleInclude<ExtArgs> | null
}
